### ISSUE TITLE
UnicodeDecodeError when parsing strings containing Japanese characters

### ISSUE THREAD

**Issue by MartinPeris** [ros-visualization/rqt_console#33] opened 2021-08-10 07:57 UTC
# What happens

rqt_console dies when double clicking a message with Japanese characters: 

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_console/console_widget.py", line 799, in _handle_mouse_double_click
    self._show_browsers()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_console/console_widget.py", line 588, in _show_browsers
    browsetext = self._model.get_selected_text(rowlist)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_console/message_data_model.py", line 219, in get_selected_text
    text += self._messages[row].pretty_print()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_console/message.py", line 129, in pretty_print
    text += '\n' + self.message + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 6: ordinal not in range(128)

```

# How to reproduce it

On a terminal execute `roscore`. On a second terminal run `rqt_console`. On a third terminal execute the following command:

```
rostopic pub /rosout rosgraph_msgs/Log "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
level: 2
name: 'test_name'
msg: 'test もしもし'
file: 'test_file'
function: 'test_function'
line: 69
topics: ['']" 
```

On the rqt_console window a line containing the message 'test もしもし' will appear. Double click on it and observe rqt_console implode

**Comment by arne48** [comment] 2021-08-11 02:27
Hello @MartinPeris,
thank you very much for creating this issue.
From your error message I can infer that you use Kinetic Kame.
Unfortunately, Kinetic is not supported anymore since April 2021.
However, it was quite a popular release and I would like to make a fix for this Unicode issue available.
But all newer ROS distributions are using python3 and therefore Unicode by default.
Because of this I wouldn't like introduce the (then in many cases) unnecessary ".decode(str)"  into the main branch.

I will check a few things on my test machines and then come back to you to talk how we could implement this maybe a little bit precise.

However, thank you very much for your engagement so that we can fix this problem.

Best,
Arne

**Comment by MartinPeris** [comment] 2021-08-11 03:08
Hi @arne48, thanks a lot for your feedback!

You are right, I am still using Kinetic Kame. I checked and it also happens in Melodic. Trying to check with ROS2 Foxy

**Comment by arne48** [comment] 2021-08-11 03:15
Hi @MartinPeris,
I tried it with my personal melodic installation so far, and that one didn't crash and showed もしもし correctly.
Noetic is the first release that was supposed to use python3 exclusively.
I didn't had time yet to do all the testing though.
But please keep me updated about your results with Foxy.

Nevertheless, once we figured out an appropriate solution, I would issue updates for all distributions >=Kinetic.

**Comment by MartinPeris** [comment] 2021-08-11 03:17
Did you try double clicking the message? The issue is not when displaying the row, but when hovering the mouse or double clicking on it

**Comment by arne48** [comment] 2021-08-11 03:22
Thanks, now it is also confirmed for Melodic and thankfully therefore now consistent with my expectation.

**Comment by MartinPeris** [comment] 2021-08-11 04:41
I tried with ROS2 Foxy and the crash does not happen. The Japanese characters appear as "squares", but that is because I am running ROS2 Foxy + Ubuntu Focal on a Docker container and my locale is not properly set.

This patch does not apply to ROS distros with Python 3

What would you propose to do?

**Comment by arne48** [comment] 2021-08-12 09:22
Yes so I wouldn't like to apply the patch to the ROS2 branch as those are Python 3 exclusive anyway.
About how I would like to implement the check I am still a bit undecided if checking for type or checking for the python version is the prettier solution.

But from the view of the logic behind the check, I would somehow check for the python version to determine if ".decode(str)" should be used or not.

**Comment by MartinPeris** [comment] 2021-08-16 01:35
On a second thought, this seems to be a minor issue that only appears with deprecated versions of Python and no one had complained about this before.

Maybe instead of tainting the code with type checks or version checks that might introduce bigger headaches down the road, the best solution might be to do nothing.

New versions ROS don't have this issue and if anyone using legacy versions encounters this crash, they can find the solution in this PR.

Shall we just close this?

**Comment by arne48** [comment] 2021-08-17 00:30
I though about this a bit more and couldn't find a satisfying way to not clutter the source code for recent versions that are running Python 3.

Therefore, I decided to branch-off for these older versions with your fix and leave the main branch as is.
I created the "melodic-devel" branch and would like to ask you to re-issue your PR against that branch.
Because Python 3 could be theoretically used, please also add the python version check to decide if ".decode()" is needed.
And also please add a Comment explaining this change again within the source.

When that is done, I will change the release sources of melodic and kinetic (maybe lunar) to the new "melodic-devel" branch.
So with having these two main branches for ROS1 I think we made a sensible decision into reduced clutter, while still fixing it and providing a patch.

Until then it was really good that @MartinPeris brought this up here, so that others who have the same problem can find a workaround for themselves.

Thanks @MartinPeris

**Comment by MartinPeris** [comment] 2021-08-17 02:48
My pleasure @arne48 

I have updated the associated PR to satisfy your requests. Please let me know if there is anything else I could do.

**Comment by arne48** [comment] 2021-08-23 10:40
Thank you @MartinPeris
Now I could merge it and I think we could successfully close this issue.

**Closed as completed by arne48** 2021-08-23 10:40 UTC
