### ISSUE TITLE
Lost messages

### ISSUE THREAD

**Issue by coalman321** [ros-visualization/rqt_console#35] opened 2021-09-11 03:28 UTC
During high message loads (multiple messages within a few ms) RQT console will drop / miss messages and not show them in the listing. Echoing /rosout confirms the messages are actually being sent, but not being picked up by RQT. I am not exactly certain what might be the issue here, but the QOS difference shown in the topic info gist, might be a good start. Default nodes seem to use TRANSIENT_LOCAL durability, whereas RQT is using VOLATILE.

Gist of the /rosout echo: https://gist.github.com/coalman321/afd12e1a6a9fa28bc0de6d294b14f20b
Gist of /rosout topic info: https://gist.github.com/coalman321/aabac832117ff9d8397d8f9471481a91 
Screenshot of the application: 
![image](https://user-images.githubusercontent.com/5054270/132934327-9bce2c41-08ca-4b89-bdac-ecb3f75416a4.png)

Version: Ros 2 Galactic (apt installation)
OS: Ubuntu 20.04
DDS: Cyclone DDS

(This issue also seems to apply on foxy as well, but I have not 100% verified that claim)

**Comment by coalman321** [comment] 2021-09-11 04:25
It looks like the QOS durability being different was the source of the issue. By changing from the system default to a custom QOS that best attempted to match the publishers on /rosout, the RQT console now captures all missing messages. There is probably a better method here for getting the correct QOS policy without it being explicitly set, so other suggestions are certainly welcome. Otherwise i'll set up a PR in the next day or so.

Screenshot of fixed console:
![image](https://user-images.githubusercontent.com/5054270/132936009-beafd40c-ce2e-496c-b32d-1beabcf72ee1.png)

link to fixing commit:
https://github.com/coalman321/rqt_console/commit/bda440c5f5cc6d6bdef520f0a4f99257b24a72f9

**Comment by arne48** [comment] 2021-09-16 03:16
Thank you very much for providing the fix.
I think as you said it should be a valid workaround for now.
I will check it get it released.
BTW did you tried it with foxy as well?

**Comment by coalman321** [comment] 2021-09-16 17:18
Currently, it has not been tested directly against foxy, but the behavior was observed to occur. I can test it tonight on my dual version system and make sure it fixes the issue as well.

**Comment by coalman321** [comment] 2021-09-25 04:07
I have been unable to test the fix against foxy until now. After a few tests, Foxy exhibits some interesting behavior. Sometimes the messages on rosout can be outright lost, even to the topic echo. This issue may be due to the default DDS change between foxy and galactic. The two examples below have no code changes between them, but have completely different behavior. It may be best to contain this fix to galactic and beyond for now. 

Example of it working properly
Topic info gist: https://gist.github.com/coalman321/d0d80a5f3a679adf849974a2458d5eb8
Topic echo Gist: https://gist.github.com/coalman321/acffc6f786e3389b7039359452ae2aba
![image](https://user-images.githubusercontent.com/5054270/134756646-49b05c52-795f-4752-84ea-f2c848064a73.png)
in this case RQT collects all messages shown in rosout via topic echo (but not all published)

Example of missing messages
Topic echo gist: https://gist.github.com/coalman321/07dcdb38d7d5903671baefc9f5018d79
![image](https://user-images.githubusercontent.com/5054270/134756646-49b05c52-795f-4752-84ea-f2c848064a73.png)
In this case, both the topic echo and rqt fail to collect all messages.

**Comment by arne48** [comment] 2021-09-27 00:53
This behavior is indeed a bit strange and might have something to do with some of the framework changes between different distributions.
I can confirm that the changes of the sources for foxy and galactic/rolling were style changes for the packaging and should not result in this behavior difference.

While I would still like to find the definitive root cause for this, it would be good to implement the hotfix for the time being.

So as you mentioned, it would be good if you could make a separate PR for galactic/rolling (ros2 branch).

**Comment by coalman321** [comment] 2021-09-27 18:33
That is very interesting. I did not know why the change occurred, but it definitely seems to have improved the situation between releases. I can change the pr to target ros2 tonight so the patch can get out. But i am certalmly interested in the boot cause here on this issue as it could have other impacts.

**Comment by arne48** [comment] 2021-10-05 07:02
Fix was merged, so this Issue can be closed.
Thank you again @coalman321.

**Closed as completed by arne48** 2021-10-05 07:02 UTC

**Comment by iwasinnam** [comment] 2025-06-12 08:11
I know that was supposedly fixed years ago, but we're experiencing the same behaviour with Humble

**Comment by arne48** [comment] 2025-06-13 06:49
Hello @iwasinnam, Thank you very much for reporting this issue when using Humble.
Which RMW are you using?
Any specific non-default configs for the RMW?
Could you please test on your system to manually increase the message_queue_depth.
You can have a look at @coalman321's PR and change the depth from 10 to maybe 100.
Thank you very much.
Lets' try to root out this issue.
